CREATE OR REPLACE TABLE USERS (
    USER_ID STRING
);

CREATE OR REPLACE TABLE IPS (
    IP_ADDR STRING
);

CREATE OR REPLACE TABLE DEVICES (
    DEVICE_ID STRING
);

CREATE OR REPLACE TABLE USER_IP_REL (
    USER_ID STRING,
    IP_ADDR STRING
);

CREATE OR REPLACE TABLE USER_DEVICE_REL (
    USER_ID STRING,
    DEVICE_ID STRING
);
