-- 02_risk_scoring.sql
-- Compute risk score per user based on shared IPs and devices

CREATE OR REPLACE VIEW FRAUDGRAPH.PUBLIC.USER_RISK AS
SELECT
    u.USER_ID,
    COUNT(DISTINCT ip.IP_ADDR) AS SHARED_IP_COUNT,
    COUNT(DISTINCT d.DEVICE_ID) AS SHARED_DEVICE_COUNT,
    LEAST(
        10,
        COUNT(DISTINCT ip.IP_ADDR) * 3
        + COUNT(DISTINCT d.DEVICE_ID) * 2
    ) AS RISK_SCORE
FROM FRAUDGRAPH.PUBLIC.USERS u
LEFT JOIN FRAUDGRAPH.PUBLIC.USER_IP_REL ip
    ON u.USER_ID = ip.USER_ID
LEFT JOIN FRAUDGRAPH.PUBLIC.USER_DEVICE_REL d
    ON u.USER_ID = d.USER_ID
GROUP BY u.USER_ID;
