-- 03_fraud_rings.sql
-- Identify fraud rings via shared IPs or devices

CREATE OR REPLACE VIEW FRAUDGRAPH.PUBLIC.FRAUD_RINGS AS
SELECT
    COALESCE(ip.IP_ADDR, d.DEVICE_ID) AS RING_ID,
    COUNT(DISTINCT u.USER_ID) AS USER_COUNT
FROM FRAUDGRAPH.PUBLIC.USERS u
LEFT JOIN FRAUDGRAPH.PUBLIC.USER_IP_REL ip
    ON u.USER_ID = ip.USER_ID
LEFT JOIN FRAUDGRAPH.PUBLIC.USER_DEVICE_REL d
    ON u.USER_ID = d.USER_ID
GROUP BY COALESCE(ip.IP_ADDR, d.DEVICE_ID)
HAVING COUNT(DISTINCT u.USER_ID) > 1;

