-- 04_coordinator_detection.sql
-- Detect coordinators based on connection counts within rings

CREATE OR REPLACE VIEW FRAUDGRAPH.PUBLIC.USER_ACTIVITY AS
SELECT
    fr.RING_ID,
    u.USER_ID,
    COUNT(DISTINCT other.USER_ID) AS CONNECTION_COUNT,
    AVG(ur.RISK_SCORE) AS AVG_RISK,
    MAX(ur.RISK_SCORE) AS MAX_RISK,
    RANK() OVER (
        PARTITION BY fr.RING_ID
        ORDER BY COUNT(DISTINCT other.USER_ID) DESC
    ) AS COORDINATOR_RANK
FROM FRAUDGRAPH.PUBLIC.FRAUD_RINGS fr
JOIN FRAUDGRAPH.PUBLIC.USERS u
    ON fr.RING_ID IS NOT NULL
JOIN FRAUDGRAPH.PUBLIC.USER_RISK ur
    ON u.USER_ID = ur.USER_ID
LEFT JOIN FRAUDGRAPH.PUBLIC.USER_IP_REL ip1
    ON u.USER_ID = ip1.USER_ID
LEFT JOIN FRAUDGRAPH.PUBLIC.USER_IP_REL ip2
    ON ip1.IP_ADDR = ip2.IP_ADDR
LEFT JOIN FRAUDGRAPH.PUBLIC.USERS other
    ON ip2.USER_ID = other.USER_ID
GROUP BY fr.RING_ID, u.USER_ID;

